# Generated by Django 4.2.4 on 2023-08-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("refbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refbook",
            options={
                "ordering": ["id"],
                "verbose_name": "Справочник",
                "verbose_name_plural": "Справочники",
            },
        ),
    ]
