# Generated by Django 4.2.4 on 2023-08-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("refbook", "0002_alter_refbook_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refbook",
            options={
                "ordering": ("id",),
                "verbose_name": "Справочник",
                "verbose_name_plural": "Справочники",
            },
        ),
        migrations.AlterModelOptions(
            name="refbookelement",
            options={"verbose_name": "Элемент", "verbose_name_plural": "Элементы"},
        ),
    ]
