# Generated by Django 4.2.4 on 2023-08-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refbook", "0004_alter_refbookversion_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refbookversion",
            name="active_from",
            field=models.DateField(unique=True),
        ),
    ]
