# Generated by Django 4.2.4 on 2023-08-15 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("refbook", "0005_alter_refbookversion_active_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refbookelement",
            name="code",
            field=models.CharField(max_length=100, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="refbookelement",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="refbookelement",
            name="refbook_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="refbook.refbookversion",
                verbose_name="Версия справочника",
            ),
        ),
        migrations.AlterField(
            model_name="refbookversion",
            name="active_from",
            field=models.DateField(unique=True, verbose_name="Действует с"),
        ),
        migrations.AlterField(
            model_name="refbookversion",
            name="refbook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="refbook.refbook",
                verbose_name="Справочник",
            ),
        ),
        migrations.AlterField(
            model_name="refbookversion",
            name="version",
            field=models.CharField(max_length=50, verbose_name="Версия"),
        ),
    ]
