# Generated by Django 4.2.4 on 2023-08-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "refbook",
            "0006_alter_refbookelement_code_alter_refbookelement_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="refbookversion",
            name="active_from",
            field=models.DateField(verbose_name="Действует с"),
        ),
        migrations.AddConstraint(
            model_name="refbookversion",
            constraint=models.UniqueConstraint(
                fields=("refbook", "active_from"), name="unique_refbook_active_from"
            ),
        ),
    ]
