# Generated by Django 4.2.4 on 2023-08-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("refbook", "0007_alter_refbookversion_active_from_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="refbookelement",
            old_name="name",
            new_name="value",
        ),
    ]
