# Generated by Django 4.2.4 on 2023-08-17 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("refbook", "0008_rename_name_refbookelement_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refbook",
            options={
                "ordering": ["id"],
                "verbose_name": "Справочник",
                "verbose_name_plural": "Справочники",
            },
        ),
        migrations.AlterModelOptions(
            name="refbookelement",
            options={
                "ordering": ["id"],
                "verbose_name": "Элемент",
                "verbose_name_plural": "Элементы",
            },
        ),
    ]
